export class Order3{
    service : number;
    paper : number;
    subject: number;
    topic : string;
    orderDesc : string;
    format : number;
    resources: number;
    resNeed : number;
    academicLevel : number;
    pages : number;
    writer : number;
    urgency: number;
    orderPrice: number;
    writerLevel : number;
    originality : boolean;
    proofRead : boolean;
    summary : boolean;
    urgentWriter : boolean;
    draft : boolean;
    custService  : number;
    isCreated: any;
    isPaid : boolean;
    isCompleted : boolean;
    orderId: any;
    time : any;
    isTBD : any;
    clientUid: string;
    clientEmail: string;
}